server:
  port: 9001
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth_server?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true # 这个表示允许我们覆盖OAuth2放在容器中的bean对象，一定要配置
  redis:
    host: localhost
    port: 6379
    database: 0

  flyway:
    enabled: true
    encoding: UTF-8
    locations: [ 'classpath:db/migration' ]
    url: jdbc:mysql://localhost:3306/auth_server?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
    user: root
    password: 123456

mybatis-plus:
  config-location: classpath:mybatis/mybatis.cfg.xml
  mapper-locations: classpath\:mybatis/mapper/*.xml
logging:
  level:
    com.example: debug